### ISSUE TITLE
Does not work with the included mgl.js

### ISSUE THREAD

**Issue by Softwave** [jonbro/mgled#4]
The included mgl.js is broken (I think?) Swapping it out with the mgl.js file from the mgl repo seems to fix the problem. I don't know if you were aware of that but I thought I'd bring it up to be sure. :) 

Also I added support for exporting games as .zip files. My code is likely terrible and I used two libraries to do it (jszip and jszip utils) and I don't know if you were wanting contributions but just an FYI. And if you were to do it yourself that is a good way to do it.

**Comment by jonbro** [comment]
oh hey! I didn't realize anyone was using this :) sorry about that. The mgl.js file that this uses is a modified version that doesn't exactly match the normal mgl coffee file, so not all the normal calls work anymore. I was in the process of removing all the short codes and left it in a bad state. Apologies for the lack of documentation on that issue :(

**Comment by jonbro** [comment]
do you mind doing a pull request of your additional features? Those sound awesome, and I would really like them in here.

**Comment by jonbro** [comment]
oh also, could you post a link to the gist of the game that wasn't working with the included mgl.js? I should be able to work out which features are broken from that. Thanks

**Comment by Softwave** [comment]
Sorry for the super late reply. 

[Simple game](https://gist.github.com/Softwave/e61e98a84382876bcd5e)

That doesn't work and pretty much anything i try doesn't work

**Comment by Softwave** [comment]
I'll try and make a pull request after i finish making sure it's decent and works

**Comment by Softwave** [comment]
Added pull request

**Comment by jonbro** [comment]
heya! thanks so much for the PRs. I have been kinda distant from this project, but hopefully will be able to take a look and merge them in soon.

**Comment by jonbro** [comment]
ok, so here is part of the problem: I was in the process of forking the library, and it made some of the functions not work as expected. I have now fixed up the functions that your simple game uses so that it actually works as expected.

I would like to continue using the included mgl.js, because it adds a few features that integrate with the editor, even though it causes a fork from the main branch of mgl.
